apiVersion: v1
data:
  ADMIN_PASSWORD: admin_pass
  ADMIN_USERNAME: admin
  DATABASE_HOST: mariadb
  DATABASE_NAME: nextcloud
  DATABASE_PASSWORD: nextcloud_pass
  DATABASE_USERNAME: nextcloud
  TRUSTED_DOMAIN_0: nc.trova.fr
kind: ConfigMap
metadata:
  labels:
    app: nextcloud-app
  name: nextcloud-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud-app
  name: nextcloud-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: nextcloud-config
                optional: false
          image: dotriver/nextcloud
          name: nextcloud-worker
          resources: {}
          volumeMounts:
            - mountPath: /var/www/nextcloud/
              name: config
            - mountPath: /var/www/nextcloud/data/
              name: data
            - mountPath: /mnt
              name: media
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/php7/
              name: php-config
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/data/default/nextcloud/config/
            type: ""
          name: config
        - hostPath:
            path: /mnt/data/default/nextcloud/nginx_config/
            type: ""
          name: nginx-config
        - hostPath:
            path: /mnt/data/default/nextcloud/php_config/
            type: ""
          name: php-config
        - hostPath:
            path: /mnt/data/default/nextcloud/data/
            type: ""
          name: data
        - hostPath:
            path: /mnt/media/
            type: ""
          name: media
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud
  labels:
    app: nextcloud-app
spec:
  selector:
    app: nextcloud-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-ingress
  labels:
    app: nextcloud-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: nc.trova.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: nextcloud
              servicePort: http
---

