apiVersion: v1
kind: ConfigMap
metadata:
  name: "jitsi-config"
  labels:
    app: "jitsi-app"
data:
  LDAP_URL: "ldap://fusiondirectory:389/"
  LDAP_BASE: "dc=trova,dc=fr"
  LDAP_BINDDN: "cn=admin,dc=trova,dc=fr"
  LDAP_BINDPW: "admin_pass"
  LDAP_FILTER: "(uid=%u)"
  LDAP_AUTH_METHOD: "bind" 
  LDAP_VERSION: "3"
  LDAP_USE_TLS: "0"
  AUTH_TYPE: "ldap"
  ENABLE_AUTH: "1"
  ENABLE_GUESTS: "1"
  XMPP_SERVER: "localhost"
  XMPP_DOMAIN: "meet.trova.fr"
  XMPP_GUEST_DOMAIN: "guest.meet.trova.fr"
  XMPP_AUTH_DOMAIN: "auth.meet.trova.fr"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.meet.trova.fr"
  XMPP_MUC_DOMAIN: "muc.meet.trova.fr"
  XMPP_BOSH_URL_BASE: "http://127.0.0.1:5280"
  XMPP_RECORDER_DOMAIN: "recorder.trova.fr"
  JICOFO_COMPONENT_SECRET: "dddddddddddddddddddddddddddddddddddddddddddddddddddddd"
  JICOFO_AUTH_USER: "focus"
  JICOFO_AUTH_PASSWORD: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
  JVB_BREWERY_MUC: "jvbbrewery"
  JVB_AUTH_USER: "jvb"
  JVB_AUTH_PASSWORD: "ooooooooooooooooooooooooooooooooooooooooooooo"
  JVB_STUN_SERVERS: "stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302"
  JVB_TCP_HARVESTER_DISABLED: "true"
  JVB_PORT: "31300"
  JVB_BREWERY_MUC: "jvbbrewery"
  TZ: "Europe/Paris"
  DOCKER_HOST_ADDRESS: "151.80.42.108"
  PUBLIC_URL: "https://meet.trova.fr"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi-app
  name: jitsi-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: jitsi-app
  template:
    metadata:
      labels:
        app: jitsi-app
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
               - {key: app, operator: In, values: [jitsi-app]}
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-5142
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "jitsi-config"
                optional: false
        - name: prosody
          image: jitsi/prosody:stable-5142
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "jitsi-config"
                optional: false
        - name: web
          image: jitsi/web:stable-5142
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "jitsi-config"
                optional: false
        - name: jvb
          image: jitsi/jvb:stable-5142
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "jitsi-config"
                optional: false
#        - name: jibri
#          image: jitsi/jibri:stable-5142
#          imagePullPolicy: Always
#         volumeMounts:          
#            - mountPath: /dev/snd
#              name: snd  
#          envFrom:
#            - configMapRef:
#                name: "jitsi-config"
#                optional: false
#      volumes:
#        - hostPath:
#            path: /dev/snd
#          name: snd

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi-app
  name: jvb-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 31300
    protocol: UDP
    targetPort: 31300
    nodePort: 31300
  selector:
    app: jitsi-app

---
apiVersion: v1
kind: Service
metadata:
  name: jitsi
  labels:
    app: jitsi-app
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: jitsi-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jitsi-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
    app: jitsi-app
spec:
  rules:
    - host: meet.trova.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: jitsi
              servicePort: http
