apiVersion: v1
data:
  OPENVPN_PROVIDER: CUSTOM
  OPENVPN_USERNAME: username
  OPENVPN_PASSWORD: password
  LOCAL_NETWORK: "10.42.0.0/16"
  TRANSMISSION_RPC_USERNAME: admin
  TRANSMISSION_RPC_PASSWORD: rpc_password
  TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
  PUID: "101"
  PGID: "102"
kind: ConfigMap
metadata:
  labels:
    app: transmission-app
  name: transmission-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission-app
  name: transmission-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission-app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: transmission-config
                optional: false
          image: haugene/transmission-openvpn
          name: transmission-worker
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: torrent
            - mountPath: /dev/net/tun
              name: tunnel
            - mountPath: /etc/openvpn/custom/default.ovpn
              name: vpngateconfig
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/data/default/transmission/config/
            type: ""
          name: config
        - hostPath:
            path: /mnt/media/Torrents/
            type: ""
          name: torrent
        - hostPath:
            path: /dev/net/tun
            type: ""
          name: tunnel
        - hostPath:
            path: /mnt/data/default/transmission/openvpnconfig.ovpn
            type: "FileOrCreate"
          name: vpngateconfig
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: transmission
  labels:
    app: transmission-app
spec:
  selector:
    app: transmission-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9091
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission-ingress
  labels:
    app: transmission-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: transmission.media.trova.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: transmission
              servicePort: http
---

