apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  labels:
    app: excalidraw-app
spec:
  selector:
    app: excalidraw-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-app
  template:
    metadata:
      labels:
        app: excalidraw-app
    spec:
      containers:
      - name: excalidraw
        image: excalidraw/excalidraw:latest

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: excalidraw-ingress
  labels:
    app: excalidraw-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: draw.trova.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: excalidraw
              servicePort: http
